# unstable_features = true

# blank_lines_upper_bound = 2

hard_tabs = true

max_width = 80
struct_variant_width = 50
struct_lit_width = 50

match_block_trailing_comma = true

reorder_modules = false

# imports_layout = "HorizontalVertical"

# fn_single_line = true

